version: '3.9'

services:
  mysql:
    image: mysql:5.7.22
    ports:
      - 3306:3306
    volumes:
      - ./mysqld:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
      - MYSQL_USER=root
      - MYSQL_DATABASE=quiz_master_db